source 'http://rubygems.nos.ncu.edu.tw'
gem 'rack-cors', :require => 'rack/cors'
gem 'rspec'
gem 'airborne'
gem 'grape'
gem 'grape-swagger', :git => 'https://github.com/tim-vandecasteele/grape-swagger.git'
